language: cpp

compiler:
  - clang

before_install:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.2-Linux-x86_64.tar.gz
  - tar xf cmake-3.2.2-Linux-x86_64.tar.gz
  - export PATH=$TRAVIS_BUILD_DIR/cmake-3.2.2-Linux-x86_64/bin:$PATH
  - export CMAKE_PREFIX_PATH=/usr/lib/insighttoolkit-4.5/cmake:$CMAKE_PREFIX_PATH
  - sudo add-apt-repository --yes ppa:jamie-snape/tubetk
  - sudo apt-get update -qq
  - sudo apt-get install -qq libinsighttoolkit-dev libjsoncpp-dev libvtk-dev

script:
  - rm -rf _build
  - mkdir _build
  - cd _build
  - cmake -DUSE_SYSTEM_ITK:BOOL=ON -DUSE_SYSTEM_JSONCPP:BOOL=ON -DUSE_SYSTEM_VTK:BOOL=ON -DTubeTK_USE_QT:BOOL=OFF -DTubeTK_USE_LIBSVM:BOOL=OFF -DTubeTK_USE_PYTHON:BOOL=OFF -DTubeTK_USE_KWSTYLE:BOOL=OFF ..
  - cmake --build .
