branches:
 only:
  - master
  - release

version: "0.0.1.{build}"

install:

  - cd ..
  - git clone https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction
  - cd ITKMinimalPathExtraction
  - curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITKPythonPackage/master/scripts/windows-download-cache-and-build-module-wheels.ps1 -O
  - ps: $env:ITK_PACKAGE_VERSION='v4.13.1.post1' ; .\windows-download-cache-and-build-module-wheels.ps1
  - cd ../ITKTubeTK
  - ps: $env:ITK_PACKAGE_VERSION='v4.13.1.post1' ; C:\Python35-x64\python.exe C:\P\IPP\scripts\windows_build_module_wheels.py

build: off

test: off

artifacts:

  # pushing entire folder as a zip archive
  - path: dist\*

deploy: off
